Feature/API Doc Monday
datadistillr/ddr_public_docs pull request #16
Opened 2022-03-30 18:56 UTC by jayaguirre

Added API data source documentation for Monday.com.

2022-03-30 20:01 UTC, MFoss19 requested changes

2022-03-30 20:01 UTC, MFoss19 commented on docs/connecting-data/connecting-to-apis-and-external-data/monday-api.md
> +For example, the Board type contains scalar fields like name, id and description. It also contains an items field, which defines the items on that specific board and contains its own fields (like nam
name, id, and description*

2022-03-30 20:01 UTC, MFoss19 commented on docs/connecting-data/connecting-to-apis-and-external-data/monday-api.md
> +The following queries are intended to help you get started, and make like simpler querying within your API.
make life* simpler

2022-03-30 20:04 UTC, jayaguirre commented on docs/connecting-data/connecting-to-apis-and-external-data/monday-api.md
> +### Costs
Like this right?

![Screen Shot 2022-03-28 at 3 01 26 PM](https://user-images.githubusercontent.com/42588877/160921419-9a58d54f-f96e-476f-a7ed-8721c6bb2aa4.png)

2022-03-31 01:58 UTC, MFoss19 approved these changes

2022-03-31 01:58 UTC, merged